version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: mt5-mongodb
    restart: unless-stopped
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongodb_data:/data/db

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: mt5-backend
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - ./backend/:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      MONGO_URI: ${MONGO_URI}
      API_PORT: ${API_PORT}
      FRONT_PORT: ${FRONT_PORT}

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: mt5-frontend
    restart: unless-stopped
    working_dir: /app
    environment:
      API_PORT: ${API_PORT}
      FRONT_PORT: ${FRONT_PORT}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "${FRONT_PORT}:${FRONT_PORT}"

  mongo-seed:
    build: 
      context: ./seed
      dockerfile: Dockerfile
      args:
        - MONGO_URI=$MONGO_URI
    depends_on:
      - mongodb

volumes:
  mongodb_data: